twig:
    default_path: '%kernel.project_dir%/templates'
    debug: '%kernel.debug%'
    strict_variables: '%kernel.debug%'
    globals:
        profile_pic_path: "User-Profile/"
        prop_images_path: "Property-Images/"

