<?php
/**
 * Created by PhpStorm.
 * User: Samurai
 * Date: 26-04-2019
 * Time: 10:01 PM
 */

namespace App\Admin;


use Sonata\AdminBundle\Admin\AbstractAdmin;
use Sonata\AdminBundle\Datagrid\DatagridMapper;
use Sonata\AdminBundle\Datagrid\ListMapper;

class AddFeaturedAdmin extends AbstractAdmin
{

    protected function configureDatagridFilters(DatagridMapper $filter)
    {
        parent::configureDatagridFilters($filter); // TODO: Change the autogenerated stub
    }

    protected function configureListFields(ListMapper $list)
    {

    }

}